### ISSUE TITLE
The woocommerce_get_page_id function is deprecated since version 3.0. Replace with wc_get_page_id

### ISSUE THREAD

**Issue by zarex360** [krokedil/woocommerce-gateway-klarna#105]
In the file woocommerce-gateway-klarna/includes/variables-checkout.php
I get this message "The woocommerce_get_page_id function is deprecated since version 3.0. Replace with "wc_get_page_id" on line 111

### Klarna plugin version

-2.3.2

### WordPress version

-3.8.1

### WooCommerce version

-3.1.2

### Klarna country

-Sweden

**Comment by slobodan** [comment]
@zarex360 thanks for reporting this, fix will be included in next release.

**Comment by slobodan** [comment]
Sorry, haven't checked your version, this was fixed in 2.3.4
