### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by WillBrubaker** [krokedil/woocommerce-gateway-klarna#107]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior
Not deprecation error
-

### Actual behavior
get deprecation
-

### Steps to reproduce the behavior
From ticket: 683146-zen

>Just installed a fresh copy of your Klarna Gateway plugin, and activated it.

>When enabling monthly cost - "Display monthly cost in product pages" - we get the following message at our product page:

>Notice: WC_Product::get_display_price er foreldet siden versjon 3.0! Bruk wc_get_price_to_display isteden.
-

### Klarna plugin version
2.4.1
-

### WordPress version
4.8.1
-

### WooCommerce version
3.0 +
-

### Klarna country

-

**Comment by slobodan** [comment]
Thanks for reporting this @WillBrubaker 

Fixed in develop branch, will be included in next release.
