### ISSUE TITLE
Duplicate orders in Klarna

### ISSUE THREAD

**Issue by jur4x** [krokedil/woocommerce-gateway-klarna#111]
### Expected behavior
For one order in webshop there must be only one order in Klarna
-

### Actual behavior
Some orders have multiple entries in Klarna
-

### Steps to reproduce the behavior
Order product by using Klarna Checkout
-

### Klarna plugin version
2.4.2
-

### WordPress version
4.7.6
-

### WooCommerce version
3.1.2
-

### Klarna country
NO
-

![klarna_website](https://user-images.githubusercontent.com/2306908/30858618-187795f8-a2c9-11e7-9fd8-c063781f5b19.png)
![website](https://user-images.githubusercontent.com/2306908/30858622-1c3af2fc-a2c9-11e7-8f34-8b371a324f64.png)
[order_log.txt](https://github.com/krokedil/woocommerce-gateway-klarna/files/1332974/order_log.txt)

**Comment by slobodan** [comment]
@jur4x does this happen with every order?

**Comment by jur4x** [comment]
@slobodan No. This is happening randomly. For example, for the same product one order can be without duplicates and then next order of the same product can be duplicated.

**Comment by slobodan** [comment]
Thanks. Does the site have any custom caching, anything that would affect WC_Session in particular?

**Comment by jur4x** [comment]
No. We are not using any cache plugins and we are not modifying anything manually in WC_Session

**Comment by slobodan** [comment]
Good. I see an error message in order log you attached and since I've never run into that particular message before, had to check with my Klarna contact what could cause it.

**Comment by slobodan** [comment]
@jur4x can you email (slobodan [at] krokedil.se) me your Klarna Checkout Norway merchant ID? Klarna needs this to check their logs.
