### ISSUE TITLE
Server error:500 on admin-ajax.php using WPML

### ISSUE THREAD

**Issue by edvinbrobeck** [krokedil/woocommerce-gateway-klarna#113]
### Expected behavior

- When completing a checkout process the order should be created in WC.
- When updating shipping method in the `[woocommerce_klarna_checkout_widget]`widget, the Klarna iframe should be updated with the updated price.

### Actual behavior

- No order is created/updated in WC but the order exists with at status of "KCO incomplete"
- When changing shipping method, the ajax requests results in a 500 error. The form data submitted is: `action:klarna_checkout_shipping_callback`and `new_method:flat_rate:7`

The exceptions is thrown by `Klarna_Checkout_BasicConnector -> verifyResponse()`and produces the following error body:
`"{"http_status_code":401,"http_status_message":"Unauthorized","internal_message":"The authorization was not correct"}"`

### Steps to reproduce the behavior

- Add item to cart, go to the specified KCO URL and try to do a checkout using the supplied test credentials by Klarna

### Klarna plugin version

- 2.4.2

### WordPress version

- 4.8.1

### WooCommerce version

- 3.1.2

### Klarna country

- SE

### WC system report
`
### WordPress Environment ###

Home URL: http://localhost
Site URL: http://localhost/wp
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.13.3
PHP Version: 7.1.7
PHP Post Max Size: 64 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (22) ###

Query Monitor: by John Blackbourn – 2.15.0
WPML Multilingual CMS: by OnTheGoSystems – 3.8.2
Advanced Custom Fields PRO: by Elliot Condon – 5.6.3
Enhanced Media Library: by wpUXsolutions – 2.4.5
Woo Preview Emails: by Digamber Pradhan – 1.2.10
WooCommerce Extended Coupon Features: by Soft79 – 2.5.4
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.0
WooCommerce Klarna Gateway: by WooCommerce – 2.4.2
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce Mapiful integration: by Edvin Brobeck –
WooCommerce Multilingual: by OnTheGoSystems – 4.2.4
WooCommerce Order Status Manager: by SkyVerge – 1.7.3
WooCommerce Product Add-ons: by WooCommerce – 2.9.0
WooCommerce Shipment Tracking: by WooCommerce – 1.6.8
WooCommerce Shipping Estimates: by SkyVerge – 2.0.0
WooCommerce: by Automattic – 3.1.2
WP Background Processing: by Delicious Brains Inc. – 1.0
WP Rocket: by WP Media – 2.10.5
WPML Media: by OnTheGoSystems – 2.2.1
WPML String Translation: by OnTheGoSystems – 2.6.2
WPML Translation Management: by OnTheGoSystems – 2.4.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #54 - /sv/butik/
Cart: #55 - /sv/varukorg/
Checkout: #56 - /sv/kassa/
My account: #57 - /sv/mitt-konto/

### Theme ###

Name: Mapiful Site V3
Version: 0.1.0
Author URL: http://mapiful.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: mapiful/.DS_Store
mapiful/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.1.0
mapiful/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.1.0

Outdated Templates: ❌Learn how to update

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: ✔
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: Eid not set Secret key not set Checkout URL not set
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Terms Page: ✔
`

**Comment by edvinbrobeck** [comment]
Update:

I tried setting SE as the default language, and update all settings/URL's accordingly.
Still seeing the same error in `admin-ajax.php` request

**Comment by slobodan** [comment]
@edvinbrobeck thanks. This is a local site, correct? Just to be sure, can you check if Klarna Checkout works as intended with all multilingual plugins disabled? Just trying to make sure the problem is not elsewhere.

**Comment by edvinbrobeck** [comment]
First to answer your question. This happens both on local (localhost) and on our staging enviroment which is public.

I have spent hours of digging in this, and the only way I can make it work if i switch the default language to Swedish (prev. EN) and the default currency to SEK prev (EUR). When doing so, the error does not occur.

I tried disabling everything in terms of plugins but woocommerce, and the klarna plugin, changing to the default WP theme (Seventeen i think it was). And the same error occured.

So my only conclusion is that this is not dependant on either theme nor other plugins.
How can I proceed? I would happily talk to someone and screen share / walk through

**Comment by edvinbrobeck** [comment]
### Update
So i discovered that if I hardcode the EID and secret in `ajax_update_klarna_order` in `class WC_Gateway_Klarna_Checkout`it works. Seems like it is not fetching the correct settings (which I am a 100% sure is entered in the right boxes, and are correct. Even validated by calling Klarna dev's today).

**Comment by edvinbrobeck** [comment]
### Update 2
When trying the same method as above on our public staging, forcing the use of the EID and secret by hardcoding it in `class-klarna-checkout.php` like this:

```
if ( 'EUR' == get_woocommerce_currency() && WC()->session->get( 'klarna_euro_country' ) ) {
    ...
} else {
    $eid          = $this->klarna_eid; // <---- Insert EID HERE
    $sharedSecret = html_entity_decode( $this->klarna_secret ); <---- Insert secret HERE
}

```
I am now able to complete the checkout without errors, the order is moved from KCO incomplete to pending, and later processing as intended.

I threw in a lot of breakpoints throughout the plugins code, and noticed that in the section above, the $this->klarna_eid and $this->klarna_secret was not set (uninitialized).

Please let me know what details you need to advise further.

**Comment by slobodan** [comment]
@edvinbrobeck can you check /includes/variables-checkout.php, the switch that begins in line 175:

```switch ( $this->shop_country ) {```

And see what `$this->shop_country` value is. If that is empty, can you please check what `$klarna_country` is set to in switch that starts in line 134 of that same file:

```switch ( $customer_selected_currency ) {```

As well as what WooCommerce built-in function `get_woocommerce_currency()` returns in that same file.

**Comment by edvinbrobeck** [comment]
Sure, will get back to you in a few minutes

**Comment by edvinbrobeck** [comment]
So i put a breakpoint at line 175 and go to the "Klarna Checkout Page"
On a full page request, it breaks there serveral times but not consistent.

Most of the time I get:
`$this->shop_country == "DE"`
`$klarna_country == "DE"`
`get_woocommerce_currency() == "EUR"`

But sometimes I get:
`$this->shop_country == "SE"`
`$klarna_country == "SE`
`get_woocommerce_currency() == "EUR"`

Which is correct

**Comment by edvinbrobeck** [comment]
So i changed method, because of the inconsistent response from breakpoint/xdebug and modified it to write to screen instead. And now i am getting consistent results.

I am dumping this at line 174
```
var_dump(array(
	"shop_country" => $this->shop_country,
	"currency" => get_woocommerce_currency(),
	"klarna_country" => $klarna_country
));
```

For each request, it logs output three times.

**First (before any other output)**
```
'shop_country' => string 'SE' (length=2)
'currency' => string 'EUR' (length=3)
'klarna_country' => string 'SE' (length=2)
```
**Second (before any other output)**
```
'shop_country' => string 'SE' (length=2)
'currency' => string 'SEK' (length=3)
'klarna_country' => string 'SE' (length=2)
```
**Third (right before the KCO iframe)**
```
'shop_country' => string 'SE' (length=2)
'currency' => string 'SEK' (length=3)
'klarna_country' => string 'SE' (length=2)
```

**Comment by edvinbrobeck** [comment]
Sorry for the excessive posting, but i noticed that the inconsistent response at first is because of the ajax requests being made on the KCO page.

In the response of the ajax requests the dump is outputted twice.

```
array (size=3)
  'shop_country' => string 'DE' (length=2)
  'currency' => string 'EUR' (length=3)
  'klarna_country' => string 'DE' (length=2)

array (size=3)
  'shop_country' => string 'SE' (length=2)
  'currency' => string 'SEK' (length=3)
  'klarna_country' => string 'SE' (length=2)
```

**Comment by slobodan** [comment]
Thanks, checking some things, can you tell me what `get_locale()` returns?

**Comment by edvinbrobeck** [comment]
It returns `sv_SE` (in the same file as above)

**Comment by slobodan** [comment]
Can we do a Skype call? Might be faster to figure it out that way. You can email me your Skype username to slobodan[at]krokedil.se

**Comment by edvinbrobeck** [comment]
Alright, you've got mail!
