### ISSUE TITLE
Errors in Klarna since WC3.2

### ISSUE THREAD

**Issue by yratof** [krokedil/woocommerce-gateway-klarna#115]
```
( ! ) Notice: WC_Cart->taxes er <strong>foreldet</strong> siden versjon 3.2! 
Bruk getters (WC_Cart::get_cart_contents_taxes()) and setters (WC_Cart::set_cart_contents_taxes()) isteden. in wp-includes/functions.php on line 3831
--
```

Methods have changed in relation to how WC gets all the cart information.

**Comment by yratof** [comment]
Looks like:

`foreach ( array_keys( WC()->cart->taxes + WC()->cart->shipping_taxes ) as $tax_rate_id )`

should be

`foreach ( array_keys( WC()->cart->get_taxes() + WC()->cart->get_shipping_taxes() ) as $tax_rate_id )`

**Comment by slobodan** [comment]
@yratof thanks for reporting. Fixed this in develop branch, will bundle it in next release
