### ISSUE TITLE
"Automatically create an account for new customers." setting checked not creating customer accounts in Woo

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#116]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- When the "Automatically create an account for new customers." setting is checked, a new Woo customer account should get created.

### Actual behavior

- No customer account is created for a new customer when this "Automatically create an account for new customers." setting is checked.

### Steps to reproduce the behavior

- Checked this setting and saved.  Created a new order with a unique email.  Order was successfully, but no account was created.

### Klarna plugin version

- Version 2.4.1

### WordPress version

-4.8.2

### WooCommerce version

-3.0.5

### Klarna country

-UK

**Comment by kristibarbosky** [comment]
Didn't see anything in the logs /var/www/vhost/wordpress/public_html/wp-content/uploads/wc-logs/ klarna-2adc9b8fcdcd14d8f29e32af6f4adf6c.log

Also tested in https://elkrokedilo.com (but there are other issues there as the orders are not getting the push notification and staying as KCO_Incomplete).

**Comment by kristibarbosky** [comment]
merchant did confirm that checking the WooCommerce->Account-> Automatically generate customer password setting did resolve this problem.  @slobodan - I don't yet see this covered in the Woo KCO plugin documentation.  Can you add that?

**Comment by slobodan** [comment]
Sorry, I had only updated Krokedil documentation page. Don't have access to WC docs site, but will have this updated too.

**Comment by slobodan** [comment]
Fixed now

https://docs.woocommerce.com/document/klarna/
