### ISSUE TITLE
Description option field for Klarna Checkout method

### ISSUE THREAD

**Issue by breadadams** [krokedil/woocommerce-gateway-klarna#119]
### Expected behavior

Ideally there should be a description field for all payment method fields. This helps when integrating methods into a 3rd party theme that can use these to modify the _default_ outputted content from the plugin.

### Actual behavior

There's only a field to modify the title.

### Steps to reproduce the behavior

Visit `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=klarna_checkout`

### Klarna plugin version

`2.4.2`

### WordPress version

`4.8.2`

### WooCommerce version

`3.2.1`

### Klarna country

_Irrelevant_

**Comment by slobodan** [comment]
Thanks @breadadams added the fix, will be included in next release.
