### ISSUE TITLE
Using deprecated methods "taxes" & "shipping_taxes" on WC_Cart

### ISSUE THREAD

**Issue by breadadams** [krokedil/woocommerce-gateway-klarna#123]
### Expected behavior

No warnings/notices.

### Actual behavior

`NOTICE: WC_CART->TAXES IS <STRONG>DEPRECATED</STRONG> SINCE VERSION 3.2! USE GETTERS (WC_CART::GET_CART_CONTENTS_TAXES()) AND SETTERS (WC_CART::SET_CART_CONTENTS_TAXES()) INSTEAD. IN /APP/PUBLIC/WP-INCLUDES/FUNCTIONS.PHP ON LINE 3831`

`NOTICE: WC_CART->SHIPPING_TAXES IS <STRONG>DEPRECATED</STRONG> SINCE VERSION 3.2! USE GETTERS (WC_CART::GET_SHIPPING_TAXES()) AND SETTERS (WC_CART::SET_SHIPPING_TAXES()) INSTEAD. IN /APP/PUBLIC/WP-INCLUDES/FUNCTIONS.PHP ON LINE 3831`

![image](https://user-images.githubusercontent.com/5795227/32169024-0de117fc-bd6f-11e7-8a49-982a10189292.png)

### Steps to reproduce the behaviour

Visit Klarna-checkout page with `WP_DEBUG` enabled.

### Klarna plugin version

2.4.2

### WordPress version

4.8.2

### WooCommerce version

3.2.1

### Klarna country

_Irrelevant_

**Comment by slobodan** [comment]
Thank you for reporting this @breadadams, it will be fixed in next release we submit to WooCommerce.

**Comment by breadadams** [comment]
Was this shipped @slobodan?

**Comment by slobodan** [comment]
@breadadams sorry, there were no releases since you opened the issue.

Should be fixed in checkout page in `develop` branch though.

**Comment by breadadams** [comment]
Hmm, wasn't `2.5.4` released 8 days ago?

![image](https://user-images.githubusercontent.com/5795227/33480659-c7dd1134-d691-11e7-8fba-3e1cfbca58bf.png)

**Comment by slobodan** [comment]
@breadadams My mistake, sorry.

Does this still happen for you in Klarna Checkout page, with 2.5.4?

**Comment by breadadams** [comment]
No problemo! Let me check... _Could_ be that client hasn't updated 😬

**Comment by slobodan** [comment]
I see WC()->cart->taxes still used in one place (so let's leave the issue open), but it should not be happening in checkout page.

**Comment by breadadams** [comment]
Checking now @slobodan - do updates for the plugin not show up via the WordPress updates screen? Or is a manual update required each time?

**Comment by slobodan** [comment]
No, it should be automatic, like any other plugin

**Comment by breadadams** [comment]
Nope, doesn't appear to be so:
![image](https://user-images.githubusercontent.com/5795227/33481746-205979fc-d696-11e7-83af-c975183d48c6.png)
(Note the _update_ banner on WooCommerce, but not on WooC. Klarna Gateway)

The plugin isn't in the WordPress plugin marketplace, it was initially installed via a manual zip upload. I guess it's cause of that?

**Comment by slobodan** [comment]
Oh, that's strange.

The plugin is distributed via woocommerce.com:

https://woocommerce.com/products/klarna/

And they handle all the updates, so it would be best to download it from there and replace the one you have (do it in staging first).
