### ISSUE TITLE
Update documentation with PHP requirements

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#130]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- [Klarna Checkout documentation](https://docs.woocommerce.com/document/klarna/?_ga=2.80069527.1642934919.1510150732-1021354840.1497427453) should include PHP requirements

### Actual behavior

- 

A merchant activated KCO plugin and it caused a FATAL error (that could only be resolved by deleting the plugin directory from the server):  
Fatal error: Can't use function return value in write context in /home4/lheilers/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout-variables.php on line 416

This was caused by an old version of PHP.

### Steps to reproduce the behavior

-

### Klarna plugin version

-

### WordPress version

-

### WooCommerce version

-

### Klarna country

-

**Comment by slobodan** [comment]
https://docs.woocommerce.com/document/klarna/
