### ISSUE TITLE
KCO not compatible with "other" payment gateways?

### ISSUE THREAD

**Issue by breadadams** [krokedil/woocommerce-gateway-klarna#131]
### Expected behavior

Should be able to checkout with any of the payment-gateways that are enabled in WooCommerce settings.

### Actual behavior

*All* orders are "hijacked" by the Klarna plugin.

Ie. when returning from a PayPal Express "popup" to the site (after successfully paying with PayPal), I'm redirected to the page set as the `Custom Checkout Page` (in admin) for the current country. An order is created in DB, but with a `kco-order-incomplete` status & the products remain in the cart.

### Steps to reproduce the behavior

We've got 2 gateways enabled, PayPal Express (via the _official_ [WooCommerce plugin](https://woocommerce.com/products/woocommerce-gateway-paypal-express-checkout/)) & Klarna Checkout (via _this_ plugin).

1. Shop base is Sweden
2. PayPal Express & Klarna Checkout enabled.
3. `Custom Checkout Page` URL set & `Overwrite is_order_received_page to return true in Klarna thank you page` is checked.
4. When "checking out" with PayPal Express no order is created (only the `kco-order-incomplete`, as mentioned above) and I'm returned to the Klarna checkout page (set via admin setting).

### Klarna plugin version

`2.4.2`

### WordPress version

`4.8.2`

### WooCommerce version

`3.2.1`

### Klarna country

Sweden

**Comment by breadadams** [comment]
This is an extremely crucial issue for us, would appreciate it if someone could check this out asap @slobodan 🙏

**Comment by breadadams** [comment]
Just guessing here, but could it be that we need to unset some of the Klarna variables from the users session when the payment-gateway isn't KCO? (Like I see happening [here](https://github.com/krokedil/woocommerce-klarna-external-payment-method/blob/master/woocommerce-klarna-external-payment-method.php#L163), in the Krokedil external-payment-method plugin.)

**Comment by slobodan** [comment]
@breadadams this only happens for PayPal Express, you have not tested it with other payment methods?

**Comment by breadadams** [comment]
That's correct @slobodan, the only gateways active here (and that we're testing with) are PayPal Express & Klarna Checkout.

Are these 2 plugins _known_ to work side-by-side?

**Comment by breadadams** [comment]
![image](https://user-images.githubusercontent.com/5795227/32694005-c4f31dc6-c735-11e7-857a-6856dea9d480.png)

Turns out the highlighted field had been **checked** mistakenly 🤦‍♂️. Unchecking it resolves the issue, as the redirect from PayPal Express popup to the "confirmation" checkout screen was getting caught in this _filter_. 

I'll leave the issue open for now as I'm not too sure whether that setting should be handling redirects in the case of it being to the confirmation screen, and it may be something you guys wanna address. If not, feel free to close it 🙂

**Comment by NiklasHogefjord** [comment]
Hi,

Sorry for not replying in this issue for a veeery long time. 

I will close this ticket since we don't have any plans to add or change functionality in the plugin. We will only maintain the plugin with bugfixes. The reason for this is that all future development will be focused on the newer Klarna checkout for WooCommerce plugin that can be found here: https://github.com/krokedil/klarna-checkout-for-woocommerce (and downloaded directly from wp.org here: https://wordpress.org/plugins/klarna-checkout-for-woocommerce/).
