### ISSUE TITLE
KCO v2 & v3 - Discount codes - Success msg missing on KCO page

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#132]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

-  Discount success message would be displayed on KCO page, similar to how the functionality works on the cart page and the Woo checkout page.

### Actual behavior

- If you fill in a discount code at shopping cart, you see the success msg stating that the code was either accepted or rejected. However, the msg for accepted codes (rejections are still shown) is not shown at the checkout page, although the code may work and the price is reduced.
If helpful I can provide a video from our demo store http://smooothpayments.com/wp3/ where the issue can be reproduced with a code "discount"

### Steps to reproduce the behavior

- Add a working discount code on the KCO page; no message is displayed.  This can be recreated at https://elkrokedilo.com/klarna-us/ and http://wp.mageklarna.com

### Klarna plugin version

- 2.5.3

### WordPress version

- 4.8.3

### WooCommerce version

- 3.2.3

### Klarna country

-tested with US & FI

**Comment by kristibarbosky** [comment]
This behavior works correctly with the newly rearchitected Woo KCOv3 plugin

**Comment by slobodan** [comment]
Fixed in `develop`
