### ISSUE TITLE
Add support for subscriptions for FI (for KCOv2)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#134]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- FI should support subscriptions in KCOv2 (just as is currently done for NO & SE)
https://developers.klarna.com/en/fi/kco-v2/checkout/use-cases

### Actual behavior

- only NO & SE currently allow subscriptions in Woo KCOv2 plugin
- note: KCOv3 does not currently support subscriptions (covers US, UK, NL); DK does not support KCO; DE & AT don't seem to support recurring (even though developers does indicate that it does, but JC & product matrix indicates that recurring is only for NO, SE, & FI)

### Steps to reproduce the behavior

-

### Klarna plugin version

-

### WordPress version

-

### WooCommerce version

-

### Klarna country

-

**Comment by slobodan** [comment]
![screen shot 2017-11-20 at 14 04 00](https://user-images.githubusercontent.com/129607/33019692-b9745d12-cdfb-11e7-80a9-76bdc8e3a7ae.png)
