### ISSUE TITLE
Checkout Hanging on iPad

### ISSUE THREAD

**Issue by yratof** [krokedil/woocommerce-gateway-klarna#135]
Tried this on several iPads on various iOS versions, can reproduce on all of them. 
There are no plugins modifying the cart other than Bring Fraktguiden Pro. Everything else is disabled for now for testing purposes.

### Example website:
https://fjellr-2255.rask22.raskesider.no/fjellrevenshop

### Steps to reproduce:

Add item to cart, head to /kasse/.

### What you'll see:

The page is unresponsive intermittently, ending in the page loading after 1.5-2 minutes, presumably when Klarna timesout

Console is saying call stack size exceeded in multiple places depending on the load:

`common.js:4093` Is returning `!! Maximum call stack size exceeded`
`common.js:4976` Is returning `!! Maximum call stack size exceeded`
`common.js:8978` Is returning `!! Maximum call stack size exceeded`
`common.js:21503` Is returning `!! Maximum call stack size exceeded`
`common.js:21521` Is returning `!! Maximum call stack size exceeded`

There doesn't seem to be an correlation other than something is eating up too much resources

There are also requests for getsentry on the page... I'm presuming that Klarna uses this, as the request says "Invalid origin: https://checkout-eu.playground.klarna.com"

### Klarna plugin version

- Versjon 2.4.0

### WordPress version

- Versjon 4.8.3

### WooCommerce version

- Versjon 3.2.3

### Klarna country

- Norway

**Comment by yratof** [comment]
Anyone able to reproduce?

**Comment by slobodan** [comment]
@yratof I am. But not on any other sites (tried two)

I noticed two things:

- This error `(index):930 GET https://fjellr-2255.rask22.raskesider.no/wp-content/themes/drivkraft-theme/assets/js/plugin/kco.js?ver=4.8.3 404 ()` can you check why this file is not loading.
- Also, from our JS file `Uncaught ReferenceError: kco_widget is not defined`, can you temporarily add this shortcode to checkout page `[woocommerce_klarna_checkout_widget]` to see if that makes a difference.

**Comment by yratof** [comment]
Sorry, the 404 is for me removing javascript that plays around with layout on the checkout, but it didn't change anything, thats back now.

I'll add the widget

**Comment by yratof** [comment]
Actually... `[woocommerce_klarna_checkout_widget]` is already added

**Comment by yratof** [comment]
I believe i've found the issue...

The Checkout width was `35.5rem`, Safari, known to not be fun with math, was sending Klarna into a loop of requesting the desktop / mobile version of klarna.

**Comment by slobodan** [comment]
I see 37.5rem in style inspector, but that one is from theme's style.css

Did removing this solve the issue?

**Comment by yratof** [comment]
it did
