### ISSUE TITLE
Emails for new KCOv2 orders not sent to store admin

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#138]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- When a KCO order is placed, as configured, the admin should receive a notification email.

### Actual behavior

- No email is sent (as confirmed by WP Mail Log plugin, see attached screen shot where 1 email was sent but 2 emails should have been sent).  When a new PayPal order is placed, emails are received as expected.  The email was sent to the customer correctly.  

The order notes in Woo show that the order correctly passed from Status der Bestellung von Incomplete Klarna Checkout auf Zahlung ausstehend geändert. (Order status of Incomplete Klarna Checkout changed to Pending Payment) to Status der Bestellung von Zahlung ausstehend auf In Bearbeitung geändert. (Status of the order from Payment pending to In process changed), see attached.

This is happening on more than 1 Woo store, but I can't recreate this on my own test store.

### Steps to reproduce the behavior

- Place a new order, check emails in WP Mail Log

### Klarna plugin version

- 2.5.3

### WordPress version

-4.9

### WooCommerce version

-3.2.3

### Klarna country

-DE

![image](https://user-images.githubusercontent.com/15654455/32906478-f7548a82-caca-11e7-8ec4-9af4c8a51784.png)

![image](https://user-images.githubusercontent.com/15654455/32906531-1ecfa696-cacb-11e7-9dfd-39b0c41244ee.png)

![image](https://user-images.githubusercontent.com/15654455/32906563-3b94e4d0-cacb-11e7-9b1c-6a5cf88d3844.png)

**Comment by slobodan** [comment]
Can we get access to staging environment? Nothing I can do without being able to replicate this.

**Comment by kristibarbosky** [comment]
Since we couldn't recreate this on any test store, it was likely an environment issue.  The merchant has terminated Klarna, so no further action needed at this time.
