### ISSUE TITLE
Errors in server log

### ISSUE THREAD

**Issue by SirRahikkala** [krokedil/woocommerce-gateway-klarna#146]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

-Not getting any errors. We have some slowdowns also.

### Actual behavior

-Errors printed to server log

### Steps to reproduce the behavior

- Just use the plugin functionalities

### Klarna plugin version

-2.5.4

### WordPress version

- 4.9.1

### WooCommerce version

-3.2.5

### Klarna country

- Finland
[errors.txt](https://github.com/krokedil/woocommerce-gateway-klarna/files/1542167/errors.txt)

**Comment by slobodan** [comment]
@SirRahikkala we never call length, width or height in our plugin.

**Comment by SirRahikkala** [comment]
Ah good point, I wonder why there is only Klarna gateway in those errors.
