### ISSUE TITLE
Cant open checkout if logged in + Adyen?

### ISSUE THREAD

**Issue by bjorngustafsson** [krokedil/woocommerce-gateway-klarna#148]
### Expected behavior
- Opening checkout would work.

### Actual behavior

- We get a 500-internal server error and checkout is not opened (We have an ajax checkout).
Serverlogs are saying : 
httpd: PHP Fatal error:  Uncaught A problem has occured in the communication to Klarna that handles our invoicing. Please contact Klarna (http://www.klarna.com) for more information or choose another payment method. (#9120)
  thrown in .../plugins/woocommerce-gateway-klarna/vendor/klarna/php-xmlrpc/src/Klarna/XMLRPC/Klarna.php on line 2594

The issue appeared when upgrading from version 2.4.2 to version 2.5.4 of woocommerce-gateway-klarna.

### Steps to reproduce the behavior
- Log in to wordpress. 
Use these Payment gateway-ids:
klarna_invoice | adyen_cse | adyen_local_payment_gateway (custom) |  paypal
Go to front-end and open checkout.

### Klarna plugin version

- 2.5.4.

### WordPress version

- 4.8.2

### WooCommerce version
- 3.1.2 (Also tested with WordPress version 4.9.1 and woocommerce version 3.2.6 and same issue appeared.)

### Klarna country
- ummm.., top-level-domain is .de so german site, but company is located in sweden.

**Comment by slobodan** [comment]
@bjorngustafsson can you send me Adyen plugin(s) so I can try to replicate this?

**Comment by NiklasHogefjord** [comment]
Closing this one due to inactivity. Please re-open the ticket if you have more info about this.
