### ISSUE TITLE
add option to set cancellation_terms_uri (for DE/AT) for KCOv2

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#149]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- Config setting under DE & AT sections for KCO where cancellation_uri can be set.

### Actual behavior

- Currently no way to set the cancellation_rights_uri for Woo in KCOv2.  See https://developers.klarna.com/en/de/kco-v2/checkout-api#merchant-object-properties  (Previous merchants have worked around this by using an anchor tag but this merchant (who is already live) has a separate page for the cancellation terms so that approach won't work).

- This is a matching request as for KCOv3 per https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/16

### Steps to reproduce the behavior

-

### Klarna plugin version

-

### WordPress version

-

### WooCommerce version

-

### Klarna country

- DE

**Comment by NiklasHogefjord** [comment]
I have a commit for this in Develop branch now - https://github.com/krokedil/woocommerce-gateway-klarna/commit/934cb95340ff07312b958e7127b2d7d39d287741.

The setting is looking like this:

![image](https://user-images.githubusercontent.com/985946/34539690-db9a176c-f0d1-11e7-8049-84489970a2ab.png)

Only available for DE & AT. Does it look ok like this?

**Comment by kristibarbosky** [comment]
thanks @NiklasHogefjord - this looks good
