### ISSUE TITLE
Hook for Checkout callback

### ISSUE THREAD

**Issue by bjorngustafsson** [krokedil/woocommerce-gateway-klarna#150]
This is a question, not a direct issue, but i couldn't add a label.

Is there a hook for the "order confirmation callback" ? In the code it says:

> In some cases the order confirmation callback from Klarna happens after the display of the thankyou page.

I would like to add an action (update order status to custom status) after the order is set to processing by klarna. I have tried with klarna_after_kco_confirmation, woocommerce_thankyou, woocommerce_order_status_pending_to_processing, woocommerce_order_status_processing. But neither of this works perfect.

**Comment by slobodan** [comment]
@bjorngustafsson sorry about late reply.

Since we use `$WC_Order->payment_complete()` to set the order to processing it would probably be best to use one of the hooks in that function, `woocommerce_payment_complete` action hook probably being the best one for your needs.
