### ISSUE TITLE
If the "push_completion" setting is disabled then orders can not be activated with klarna.

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/woocommerce-gateway-klarna#154]
### Expected behavior

There should be a button on the admin order page to active the order with klarna

### Actual behavior

Currently the only way an order can be activated is if "push_completion" is activated and the order status is changed to completed. 
If the push_completed is disabled the only way to activate an order with klarna is to enable the setting and then changing the order status from completed to anything else, eg.: on-hold and then back to completed. On a normal Woo installation this triggers order-status emails to be sent to the customers (which is bad, because they already received an order-completed email from before).

**Comment by forsvunnet** [comment]
The same goes for the other actions as well. There should be a button for cancelling or updating an order as well.

**Comment by slobodan** [comment]
@forsvunnet this is a great idea, but it's not something we will implement in this plugin.

The reason for that is that this (old) plugin is being replaced by a family of smaller plugins (one for each payment method, plus one for order management) that will have a smaller footprint, better implementation with WooCommerce checkout process and work with the latest family of Klarna offerings (Klarna Checkout V3 and Klarna Payments).

https://woocommerce.com/product-category/woocommerce-extensions/?q=klarna

We worked both with Klarna and Automattic to get this done.

That means this plugin is going to be maintained, but we do not plan to do any new development on it, but your suggestion makes a lot of sense for new Order Management plugin, so I'm adding an issue to its repo:

https://github.com/krokedil/klarna-order-management-for-woocommerce/issues/8
