### ISSUE TITLE
PHP Fatal error in /includes/variables-checkout.php:352 (Blocks recurring payments!)

### ISSUE THREAD

**Issue by jelgblad** [krokedil/woocommerce-gateway-klarna#156]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

No fatal error in debug.log.

### Actual behavior

```
[05-Feb-2018 06:43:54 UTC] PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /home/xxxxx/public_html/wp-content/plugins/woocommerce-gateway-klarna/includes/variables-checkout.php:352
Stack trace:
#0 /home/xxxxx/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(31): include()
#1 /home/xxxxx/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-checkout.php(1470): WC_Gateway_Klarna_Checkout->__construct()
#2 /home/xxxxx/public_html/wp-includes/class-wp-hook.php(286): WC_Gateway_Klarna_Checkout_Extra->start_session('')
#3 /home/xxxxx/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /home/xxxxx/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /home/xxxxx/public_html/wp-settings.php(450): do_action('init')
#6 /home/xxxxx/public_html/wp-config.php(114): require_once('/home/xxxxx/...')
#7 /home/xxxxx/public_html/wp-load.php(37): require_once('/home/xxxxx/...')
#8 /home/xxxxx in /home/xxxxx/public_html/wp-content/plugins/woocommerce-gateway-klarna/includes/variables-checkout.php on line 352
```

Woocommerce Subscriptions also aren't creating any renewal orders. Don't now if related at all, but it seems to have started after we upgraded to WooCommerce 3.3.0.
Maybe this is blocking renewal orders, since it's Fatal...?

### Steps to reproduce the behavior

Install versions below and just hit the page.

### Klarna plugin version

2.5.6

### WordPress version

4.9.2

### WooCommerce version

3.3.0

### Klarna country

Sweden

**Comment by jelgblad** [comment]
https://github.com/krokedil/woocommerce-gateway-klarna/blob/d44e722e7aa9fa485eb98229ea83c5b187dc322d/includes/variables-checkout.php#L352

**Comment by slobodan** [comment]
Fixed in latest
