### ISSUE TITLE
Issue with KCO when using multiple gateways

### ISSUE THREAD

**Issue by edvinbrobeck** [krokedil/woocommerce-gateway-klarna#158]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

We support multiple payment methods, including KCO, Stripe and Paypal. The issue is that when a customer first tries to pay using stripe/paypal but does not suceed, and continue and try to pay using Klarna.  The customer is charged by klarna, but the order flow in woocommerce fails. **This is critical due to the fact that the customer gets charged, but WC deems the order as failed hence not completing any following automated actions (emails etc)**

### Expected behavior

- The order should be processed just as usual.

### Actual behavior

- An order object is created during the first failed attempt (stripe). with a status of failed, and when trying to fulfill the klarna flow the "Thankyou page" is never rendered due to a fatal PHP error 
`Uncaught Error: Call to a member function get_user_id() on boolean in /var/www/html/content/plugins/woocommerce-gateway-klarna/includes/checkout/thank-you.php:109 `

See screenshot
https://ibb.co/bwyvFc

I dug a bit further and the thank you page is unable to render due to that there is no Order ID for it to use. According to the code there should be a $_GET var named `order-received` but the URL that is redirected is:
`<kco-checkout-url>?klarna_order=7ZPWKWCN8SS75R8OMSYFK9JFF9Y&scountry=SE&thankyou=yes` and thus missing the required variable.

### Steps to reproduce the behavior

1. Try and fulfill an order using stripe but fail the attempt with the "card_declined" reason, using a test card `4000 0000 0000 0002`. This happens i.e. when a swedish customers bank need 3d_secure and to sign using BankID.
2. Switch payment method to Klarna and try to complete the order.

### Klarna plugin version

-Version 2.5.6

### WordPress version

- 4.9.2

### WooCommerce version

- 3.2.6

### Klarna country

- Sweden

**Comment by slobodan** [comment]
@edvinbrobeck when you check out with KCO (no Stripe involved), the thank you page URL will look something like this:

http://site.url/?klarna_order=KLARNAORDERID&sid=2165&scountry=SE&order-received=2165&thankyou=yes&key=wc_order_5a79c5c27c787

Even after failed Stripe attempt, using card number you have sent, and it still worked.

Can you share your Stripe settings (other than credentials), so I can be sure I'm trying to reproduce this the correct way.

**Comment by turansadri** [comment]
We get the same error message from time to time and the order is not coming through to Woocommerce although it's created in Klarna and the customer is charged.

I however have no idea why this is happening, but we also have PayPal as an alternative payment gateway. 

@slobodan I can send you the error report from Sentry via email if that could help?

**Comment by slobodan** [comment]
@turansadri please do (my_github_account[at]krokedil.se)

**Comment by Tobias-Conrad** [comment]
i use the free PPPlus Plugin and can not confirm this issue.

**Comment by NiklasHogefjord** [comment]
Sorry for the very late reply. This issue should however be solved in the 2.5.15 release: https://github.com/krokedil/woocommerce-gateway-klarna/releases/tag/2.5.15
