### ISSUE TITLE
Update order created date when payment is created

### ISSUE THREAD

**Issue by thomasandersen** [krokedil/woocommerce-gateway-klarna#16]
Hi

KCO creates the local WooCommerce order when the end user initially visits the checkout page. 

If the end user / customer does not submit the order that day but instead waits 1 day for whatever reason, the order will have the post/order date set to 'yesterday'. 
This may cause confusion for store managers as shop orders are not sorted as expected.
While the incomplete order 'sits' there new orders are created and paid and when the incomplete order is finally paid 1 day after it may 'disappear' from the list for some managers

I know the logic KCO is doing is correct, but it is not as apparent to managers that the order is created on initial visit to the checkout.

A solution would be that KCO updates the order's post_date when the payment is created.

### Expected behavior
Order / post date to be the date when payment is created
-

### Actual behavior
Order / post date is when the order is created date (initial checkout page visit)
-

### Steps to reproduce the behavior
1. Add items to cart
2. Visit checkout 
3. Wait eg. 5 minutes
4. Submit order

-

### WordPress version
4.6.1
-

### WooCommerce version
2.6.8
-

### Klarna country
Norway
-

**Comment by slobodan** [comment]
@thomasandersen thank you for reporting this. While I think this is probably an edge case, it still should be fixed, to avoid confusion.

We will look into this for next release.

**Comment by slobodan** [comment]
Just pushed another update, that happens to fix this one as well.
