### ISSUE TITLE
406 POST error due to empty or standard cURL user-string

### ISSUE THREAD

**Issue by jagboon** [krokedil/woocommerce-gateway-klarna#162]
### Expected behavior
Order is created in backend
-

### Actual behavior
Order is not created in backend
-

### Steps to reproduce the behavior
Complete checkout and pay with credit card
-

### Klarna plugin version
2.5.7
-

### WordPress version
4.9.4
-

### WooCommerce version
3.3.1
-

### Klarna country
Sweden
-
Getting a 406 error when the POST request is made to create orders in backend.
Been in contact with our hosting provider and they have informed me, that the error occurs because they don't allow POST requests when the cURL user-agent is either empty or standard.

Extract of the webserver log.
192.71.255.70 - - [19/Feb/2018:14:19:24 +0100] "POST /wc-api/WC_Gateway_Klarna_Checkout/?sid=19636&scountry=SE&klarna_order=5Z6XPUQUTHIV73499NHDCVYMJPC&klarna-api=v2" 406 102 "-" "-"

**Comment by slobodan** [comment]
Hi,

This request comes directly from Klarna, our plugin only listens to it. I'm afraid you will have to either get in touch with Klarna directly and see if you can resolve this with them or advise your hosting provider to allow such requests.

**Comment by jagboon** [comment]
Hey,

Thanks for the fast reply. I'll take the problem to KLARNA and see what they have to say.

**Comment by kristibarbosky** [comment]
@jagboon - If/when you get a Klarna support case number, please add that to this ticket.  I've found the right team within Klarna to research this issue and expect a response tomorrow.

**Comment by kristibarbosky** [comment]
@jagboon - So far all I've found is that the behavior has been this way for a very long time.  Has something changed on your side causing you to raise this issue now?

**Comment by jagboon** [comment]
@kristibarbosky - Yes. He recently move to a different web host. I recognise that webserver setup differs from host to host, but a declared user-agent should not be difficult to add to the POST string and ought not cause to web servers with a less secure configuration.

**Comment by kristibarbosky** [comment]
@jagboon - I've created the ticket to hopefully get this fixed and will let you know when it has been released, possibly next week.

**Comment by jagboon** [comment]
@kristibarbosky Thank you. I just received a reply from KLARNA and they apparently needed more information. It's a little late but now I have a reference number to give you 04753039.
