### ISSUE TITLE
If a user is logged in, but uses a different email in KCO iframe, the order should still be attributed to that logged in user

### ISSUE THREAD

**Issue by slobodan** [krokedil/woocommerce-gateway-klarna#164]
Currently, customer ID is assigned to the order on push listener, where Klarna order billing email is checked, and the order is assigned to the (WordPress) user that has that email, if the email exists.

It would be better to always assign the order to logged in user, but what should be done with order and customer email in that case:

- Should both order email and customer email be set to this new email?
- Should only order email be set to new email, keeping the customer registered email address as is?
- Should we just ignore the new email and use old customer email for both order and customer?

**Comment by slobodan** [comment]
@NiklasHogefjord @MichaelBengtsson can I get your thoughts on this?

**Comment by slobodan** [comment]
@fraubungle I agree with you.

You can grab latest code, with the fix you suggested, from develop branch in this repo.

**Comment by NiklasHogefjord** [comment]
Fixed in 1ece08398e1b8a0b86060378bd895d0440c7dea0
