### ISSUE TITLE
Can't process orders when logging is enabled

### ISSUE THREAD

**Issue by zamson** [krokedil/woocommerce-gateway-klarna#166]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

Order received / thank you page when placing order.

### Actual behavior

Error 200 stuck at checkout when using Klarna invoice gateway (not KCO). Invoice is created in Klarna but response does not send the visitor to thank you page. Order status is failed in Dashboard but Klarna invoice is created anyways. Deactivating logging solves the problem.

`2018/03/11 16:38:47 [error] 30662#30662: *3353 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function add() on null in /home/forge/example.com/web/app/plugins/woocommerce-gateway-klarna/classes/class-klarna-invoice.php:677
Stack trace:
#0 /home/forge/example.com/web/app/plugins/woocommerce/includes/class-wc-checkout.php(804): WC_Gateway_Klarna_Invoice->process_payment(54695)
#1 /home/forge/example.com/web/app/plugins/woocommerce/includes/class-wc-checkout.php(986): WC_Checkout->process_order_payment(54695, 'klarna_invoice')
#2 /home/forge/example.com/web/app/plugins/woocommerce/includes/class-wc-ajax.php(409): WC_Checkout->process_checkout()
#3 /home/forge/example.com/web/wp/wp-includes/class-wp-hook.php(286): WC_AJAX::checkout('')
#4 /home/forge/example.com/web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /home/forge/example.com/web/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /home/forge/example.com/web/app/plugins/woocommerce/includes/class-wc-ajax.php(" while reading response header from upstream, client: x.x.x.x, server: example.com, request: "POST /?wc-ajax=checkout HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "example.com", referrer: "https://example.com/kassa/"
2018/03/11 16:40:11 [error] 30662#30662: *3353 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function add() on null in /home/forge/example.com/web/app/plugins/woocommerce-gateway-klarna/classes/class-klarna-invoice.php:677`

### Steps to reproduce the behavior

Place order with Klarna invoice and make sure to have Klarna logging active so troublesome function (add()) is run.

### Klarna plugin version

2.5.8

### WordPress version

4.9.4

### WooCommerce version

3.2.1

### Klarna country

Sweden

**Comment by NiklasHogefjord** [comment]
Hi,

Very sorry for the extremely late reply.

If you update to the latest version of the Klarna plugin (at the moment version 2.5.15) this issue will probably be solved.
