### ISSUE TITLE
Delivery date plugin and custom fields in checkout

### ISSUE THREAD

**Issue by asmundsollihogda** [krokedil/woocommerce-gateway-klarna#167]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

Showing delivery date calendar (WooCommerce Order Delivery).

### Actual behavior

Not showing the delivery date options in checkout. The field is probably shown using hooks. Is there a way to use hooks and custom checkout fields with the Klarna plugin?

### Steps to reproduce the behavior

Use the delivery date plugin.

### Klarna plugin version

2.5.10

### WordPress version

4.9.4

### WooCommerce version

3.3.3

### Klarna country

Norway

**Comment by NiklasHogefjord** [comment]
Sorry for the veeery late reply. You have probably solved this or found another solution for this already. But just as information - we don't have a good way to solve this within the plugin. 

You could use one of the hooks in the cart widget (for instance kco_widget_after, https://github.com/krokedil/woocommerce-gateway-klarna/blob/master/classes/class-klarna-shortcodes.php#L394) to display an extra form field. But the changes in that field needs to be stored programatically by your code (preferably via ajax).

This plugin is no longer in active development. We are fixing bugs and maintaining it but future development will be done in the new Klarna Checkout plugin (for Klarnas v3 platform). More info can be found here: https://github.com/krokedil/klarna-checkout-for-woocommerce & here https://wordpress.org/plugins/klarna-checkout-for-woocommerce/.
