### ISSUE TITLE
Logging broken - Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#168]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- No errors

### Actual behavior

I have not recreated this locally yet, but hopefully the stack trace below provides sufficient info:

-[21-Mar-2018 10:43:21 UTC] PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /home/rchobbypro/public_html/wp-includes/functions.php:440
Stack trace:
#0 [internal function]: ArrayObject->serialize()
#1 /home/rchobbypro/public_html/wp-includes/functions.php(440): serialize(Array)
#2 /home/rchobbypro/public_html/wp-includes/meta.php(80): maybe_serialize(Array)
#3 /home/rchobbypro/public_html/wp-includes/meta.php(202): add_metadata('post', 66516, '_krokedil_order...', Array)
#4 /home/rchobbypro/public_html/wp-includes/post.php(1804): update_metadata('post', 66516, '_krokedil_order...', Array, '')
#5 /home/rchobbypro/public_html/wp-content/plugins/woocommerce-gateway-klarna/vendor/krokedil/krokedil-logger/src/krokedil-order-event-log.php(81): update_post_meta('66516', '_krokedil_order...', Array)
#6 /home/rchobbypro/public_html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-to-wc.php(321): krokedil_log_events('66516', 'Klarna listener...', Object(Klarna\Rest\OrderManagement\Order))
#7 /home/rchobbypro/publ in /home/rchobbypro/public_html/wp-includes/functions.php on line 440

### Steps to reproduce the behavior

-

### Klarna plugin version

- 2.5.10

### WordPress version

- 3.3.4

### WooCommerce version

-

### Klarna country

- US

WordPress status report:

### WordPress Environment ###
 
Home URL: https://rchobbypro.com
Site URL: https://rchobbypro.com
WC Version: 3.3.4
Log Directory Writable: ?
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ?
Language: en_US
 
### Server Environment ###
 
Server Info: Apache
PHP Version: 7.1.15
PHP Post Max Size: 50 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.0.2n
 
SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 50 MB
Default Timezone is UTC: ?
fsockopen/cURL: ?
SoapClient: ?
DOMDocument: ?
GZip: ?
Multibyte String: ?
Remote Post: ?
Remote Get: ?
 
### Database ###
 
WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ?
Total Database Size: 322.05MB
Database Data Size: 235.92MB
Database Index Size: 86.13MB
wp_woocommerce_sessions: Data: 4.43MB + Index: 0.12MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 4.04MB + Index: 1.68MB
wp_woocommerce_order_itemmeta: Data: 19.61MB + Index: 12.78MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_aps_social_icons: Data: 0.00MB + Index: 0.00MB
wp_aws_cache: Data: 0.00MB + Index: 0.00MB
wp_aws_index: Data: 9.14MB + Index: 0.00MB
wp_commentmeta: Data: 0.07MB + Index: 0.05MB
wp_comments: Data: 10.30MB + Index: 5.04MB
wp_cpf_custom_products: Data: 0.00MB + Index: 0.00MB
wp_cpf_google_merchant_feed_products: Data: 0.02MB + Index: 0.02MB
wp_cp_feeds: Data: 0.00MB + Index: 0.00MB
wp_es_deliverreport: Data: 0.01MB + Index: 0.00MB
wp_es_emaillist: Data: 0.22MB + Index: 0.02MB
wp_es_notification: Data: 0.00MB + Index: 0.00MB
wp_es_pluginconfig: Data: 0.00MB + Index: 0.00MB
wp_es_sentdetails: Data: 0.01MB + Index: 0.00MB
wp_es_templatetable: Data: 0.00MB + Index: 0.00MB
wp_ewwwio_images: Data: 4.75MB + Index: 1.92MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_gaplus_login: Data: 0.02MB + Index: 0.00MB
wp_google_merchant_cp_feeds: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.08MB + Index: 0.00MB
wp_omega_index_status: Data: 36.61MB + Index: 0.00MB
wp_omega_sync_status: Data: 0.02MB + Index: 0.03MB
wp_options: Data: 12.38MB + Index: 0.27MB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 52.07MB + Index: 26.33MB
wp_posts: Data: 6.25MB + Index: 1.66MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB
wp_revslider_slides: Data: 0.01MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_rs_templates_email: Data: 0.00MB + Index: 0.00MB
wp_shipworks_bridge: Data: 0.00MB + Index: 0.00MB
wp_sumo_reward_encashing_submitted_data: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.07MB + Index: 0.06MB
wp_terms: Data: 0.02MB + Index: 0.05MB
wp_term_relationships: Data: 0.14MB + Index: 0.25MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 63.63MB + Index: 28.62MB
wp_users: Data: 3.20MB + Index: 2.33MB
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_points_rewards_user_points: Data: 1.60MB + Index: 2.16MB
wp_wc_points_rewards_user_points_log: Data: 3.27MB + Index: 1.73MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.23MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.01MB + Index: 0.01MB
wp_wfFileMods: Data: 1.66MB + Index: 0.37MB
wp_wfHits: Data: 0.00MB + Index: 0.00MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.01MB + Index: 0.00MB
wp_wfKnownFileList: Data: 0.83MB + Index: 0.11MB
wp_wfLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_wfLogins: Data: 0.08MB + Index: 0.02MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.00MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.05MB + Index: 0.10MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.14MB + Index: 0.06MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB
wp_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.03MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.26MB + Index: 0.27MB
 
### Post Type Counts ###
 
attachment: 3442
custom_css: 1
customize_changeset: 4
mkhb_header: 1
nav_menu_item: 58
oembed_cache: 7
page: 24
post: 5
product: 982
product_variation: 1217
revision: 364
scheduled-action: 1
shop_coupon: 4
shop_order: 14425
shop_order_refund: 473
shop_subscription: 5
wpcf7_contact_form: 5
wpl_wpcp_shortcodes: 49
 
### Security ###
 
Secure connection (HTTPS): ?
Hide errors from visitors: ?
 
### Active Plugins (19) ###
 
ManageWP - Worker: by ManageWP – 4.5.0
Autoptimize: by Frank Goossens (futtta) – 2.3.2
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Facebook for WooCommerce: by Facebook – 1.6.0 – Not tested with the active version of WooCommerce
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.3.1.1
Heartbeat Control: by Jeff Matson – 1.2.3
Hello Bar (Official): by Hello Bar – 1.0
WPBakery Page Builder (Modified Version): by Michael M - WPBakery.com – 5.4.5.1
MailChimp for WooCommerce: by MailChimp – 2.1.5 – Not tested with the active version of WooCommerce
Omega Instant Search For WooCommerce: by Omega Search – 1.6.11 – Not tested with the active version of WooCommerce
Tidio Chat: by Tidio Ltd. – 3.3.0
Cookie Consent: by Catapult_Themes – 2.3.9
WooCommerce Product Carousel Pro: by WPLimb – 1.6.1 – Not tested with the active version of WooCommerce
WooCommerce Klarna Gateway: by WooCommerce – 2.5.10 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.4
WooCommerce: by Automattic – 3.3.4
Yoast SEO: by Team Yoast – 7.1
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.6.4 – Not tested with the active version of WooCommerce
 
YITH WooCommerce Order Tracking Premium: by YITHEMES – 1.4.3
 
### Settings ###
 
API Enabled: ?
Force SSL: ?
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable-subscription (variable-subscription)
 
Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
 
 
### WC Pages ###
 
Shop base: #26 - /shop/
Cart: #27 - /cart/
Checkout: ? Page does not contain the shortcode.
My account: #29 - /my-account/
Terms and conditions: #973 - /terms-and-conditions/
 
### Theme ###
 
Name: Jupiter
Version: 6.1.1
Author URL: http://themeforest.net/user/artbees
Child Theme: ? – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ?
 
### Templates ###
 
Overrides: jupiter/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.3.0
jupiter/woocommerce/content-product.php
jupiter/woocommerce/content-product_cat.php
jupiter/woocommerce/loop/add-to-cart.php
jupiter/woocommerce/loop/loop-end.php
jupiter/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
 
Outdated Templates: ?Learn how to update
 
### Klarna ###
 
Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status
 
Sweden: Eid not set Secret key not set Checkout URL not set
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: Eid not set Secret key not set Checkout URL not set
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: ?
Terms Page: ?

**Comment by NiklasHogefjord** [comment]
Should be fixed in ce45791fd5f7626dfb8d24b942c0365aa8447b88
