### ISSUE TITLE
Add plugin version to User-Agent

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#169]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- Current User-Agent: "Library/Krokedil_2.1.0 (Guzzle/5.3.1; curl/7.58.0) OS/Linux_2.6.32-696.20.1.el6.x86_64 Language/PHP_7.1.15",

### Actual behavior

- Add plugin version to User-Agent above (e.g. "woocommerce-gateway-klarna1.2.4")

### Steps to reproduce the behavior

- place a KCO order using woocommerce-gateway-klarna

### Klarna plugin version

-

### WordPress version

-

### WooCommerce version

-

### Klarna country

-

**Comment by NiklasHogefjord** [comment]
Add plugin slug + version number

**Comment by MichaelBengtsson** [comment]
Closed, we wont be doing this since the v2 platform will be discontinued next year.
