### ISSUE TITLE
push notifications fail with 500 error for KCOv3 on plugin version2.5.11

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#173]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- push notifications should succeed and KCOv3 orders should get created in WooCommerce, such as per this sample entry from Klarna logs:

message:	 Successfully posted confirmation to [https://merchantsite.com/wc-api/WC_Gateway_Klarna_Checkout/?sid=71513&scountry=US&klarna_order=xxxxxxx&wc-api=WC_Gateway_Klarna_Checkout&klarna-api=rest] in 4379 ms, response: [200]	
  	 timestamp:	 2018-05-03T03:08:09.526Z

### Actual behavior

- 	 message:	 Failed to post confirmation for to [https://merchantsite.com/wc-api/WC_Gateway_Klarna_Checkout/?sid=24645&scountry=GB&klarna_order=xxxxxxxxxxxxxx&wc-api=WC_Gateway_Klarna_Checkout&klarna-api=rest] in 178 ms, response: [500]	
  	 timestamp:	 2018-05-09T15:25:04.035Z	

### Steps to reproduce the behavior

- Without changing any configuration settings, tested at http://wp.mageklarna.com/
using 2.5.7, orders were successfully created in Woo 
using 2.5.11, the push confirmation from Klarna always received a 500 error code & orders never changed from the KCO Incomplete status to Processing status in Woo

### Klarna plugin version

- 2.5.11

### WordPress version

- 4.9.5

### WooCommerce version

-3.3.5

### Klarna country

- US & UK

**Comment by NiklasHogefjord** [comment]
Fixed in 996fcaaea03800d332800255399095a7e7f14387
