### ISSUE TITLE
Class 'Klarna_Checkout_For_Woocommerce_GDPR' not found

### ISSUE THREAD

**Issue by eaglevisionit** [krokedil/woocommerce-gateway-klarna#178]
There is a error:

```
Fatal error: Uncaught Error: Class 'Klarna_Checkout_For_Woocommerce_GDPR' not found in /var/www/html/renoverahuset/wp-content/plugins/woocommerce-gateway-klarna-2.5.14/classes/class-klarna-gdpr.php:43 
```

Solution:
in `/wp-content/plugins/woocommerce-gateway-klarna-2.5.14/classes/class-klarna-gdpr.php`  class name
`WC_Gateway_Klarna_GDPR`   should be `Klarna_Checkout_For_Woocommerce_GDPR`

**Comment by NiklasHogefjord** [comment]
Hi,
Thanks for the report! This issue was solved in 1954bb89f60531742ed387f1a98670c272a5cdfb but I had forgot to update the release.

It should have been fixed now.
