### ISSUE TITLE
Generalize stidner specific cart update

### ISSUE THREAD

**Issue by ErikBernskiold** [krokedil/woocommerce-gateway-klarna#180]
On line 258 of klarna-checkout.js, there is a specific bit of code for the Stidner plugin compatibility.

The block above, and this, is responsible for updating shipping in Klarna.

Let's assume one is using a custom shipping method input (as the Stidner plugin is). Then there is no way to 'hook' into the `update_klarna_shipping` function, which the `klarna_update_shipping` listener otherwise is indented to do.

Proposed fix is the following:

`$(document.body).on('klarna_update_shipping', function(event, id) {
update_klarna_shipping(id);
});`

That way, we can call it using the trigger:

`$(document.body).trigger('klarna_update_shipping', shipping_method);`

where `shipping_method` would be the method ID in WooCommerce.

PS: There are also two console logs on lines 297 and 299 that shouldn't be there.

**Comment by ErikBernskiold** [comment]
Ping @NiklasHogefjord :)

**Comment by NiklasHogefjord** [comment]
Thanks for the report @ErikBernskiold.

We have updated the plugin with your suggestion now. The fix managed to sneak into another commit so it's a bit messy, but here it is: afc8ffde549f0fd3d59db293034733942854c98a.

This code is still in the Develop branch but will be included in the next release.
