### ISSUE TITLE
Is necesary have krokedil on production?

### ISSUE THREAD

**Issue by killua99** [krokedil/woocommerce-gateway-klarna#183]
My concern is about using krokedil log events like 7 times.

For production sites we could implement a flag to stop logging those event or disable that module / vendor at all?

**Comment by NiklasHogefjord** [comment]
Hi,

Sorry for the late reply. We will look through this and possibly remove the krokedil_log_events() feature in favour for using the regular WC logging feature in another way.

I'll go through this and will keep you posted here in this issue.

**Comment by NiklasHogefjord** [comment]
@MichaelBengtsson perhaps we can take a look at this together?

**Comment by killua99** [comment]
Perhaps this is too old, feel free to close it

**Comment by MichaelBengtsson** [comment]
@killua99 Yes sorry this plugin and the API it works with has been deprecated a while ago. We should probably have cleaned this up a while ago.
