### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by JKetelaar** [krokedil/woocommerce-gateway-klarna#23]
I made this PR: https://github.com/krokedil/woocommerce-gateway-klarna/pull/21
Just a quick question mattering this pull request; when do you think it will be released as a plugin? As this is quite a critical matter for a few clients of ours.

Looking forward to your response!

**Comment by slobodan** [comment]
@JKetelaar working on new release now, and we'll likely have it released during the week. And thanks again for the PR.
