### ISSUE TITLE
New order email not being sent

### ISSUE THREAD

**Issue by knubbbe** [krokedil/woocommerce-gateway-klarna#26]
### Expected behavior
When a new order is created by guest customer (no registration enabled on website), a email is sent to the customer and admin that a new order was created.

### Actual behavior
No emails is being sent.

### Steps to reproduce the behavior
Create order as guest with Checkout.

### WordPress version
4.7 (and earlier)

### WooCommerce version
2.6.8 
Klarna Gateway v2.2.3

### Klarna country
Sweden

**Comment by slobodan** [comment]
@knubbbe I'm not able to reproduce this.

Tried following:

Logged out
Create new order using Klarna Checkout
In Klarna Checkout use an email that is not associated with an existing account
In Klarna Checkout settings tried with option to "Create customer account" disabled and enabled (two separate tests)

In both cases emails to store manager and customer were sent.

Can you try deactivating any other plugins that might interfere, or install WP Mail Logging plugin, to see if it catches the emails?

**Comment by knubbbe** [comment]
Hey @slobodan !
Thanks for quick response.

I installed WP Mail Logging just to see if mail actually was sent, but they were not.
Then I tried disabling some plugins that might interfere:

- Activity Log
- Contact Form 7
- iThemes Security
- WooCommerce Helper (just in case)
- WooCommerce Store Exporter (again just in case)

When I disabled **iThemes Security** it worked when I tried creating a new order. Mail were sent!
The weird part is that when I re-enabled **iThemes Security** it still worked.

So I don't know if **iThemes Security** resets some settings when inactivating it or not (I didn't change any settings manually).

I'm glad that it works now, but abit frustrated that I don't know exactly why..

Again, thanks for the quick response!

**Comment by slobodan** [comment]
Strange issue really, but glad to hear it's solved!
