### ISSUE TITLE
Maybe update KCO behaviour/flow if guest purchases are not allowed

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/woocommerce-gateway-klarna#27]
Compare it with how it's handled in Woo's own checkout. 

When I tested in standard checkout you didn't need to create an account first. You just fill in the checkout form but when the purchase is done an account is created for you. Perhaps we should do this in KCO as well? Or remove the "Add account" setting?

Let's discuss :)

**Comment by boozebrorsan** [comment]
I have received a wish for this too from Support emails.

**Comment by boozebrorsan** [comment]
Suggestions from a support ticket (in swedish):

Jag skulle personligen föredra om ni inte tog bort "Add account"-möjligheten. Jag vill personligen att KCO ska fungera exakt som den vanliga kassan, av den enkla anledningen att vi inte vill tillåta gästköp. Skulle ni designa KCO på det sättet så skulle administratören ha total valfrihet också, vilket så klart är positivt. :) Detta skulle dock "kräva" att ni lägger till en möjlighet att logga in från själva kassasidan. I butiken är följande inställt: 

- WP Admin -> WooCommerce -> Inställningar -> Kundkonton -> Aktivera registrering -> **Möjliggör registrering i kassan (ibockat)** 
- WP Admin -> WooCommerce -> Inställningar -> Kundkonton -> Aktivera registrering -> **Möjliggör registrering på Mitt konto-sidan (ibockat)** 
- WP Admin -> WooCommerce -> Inställningar -> Kundkonton -> Skapa konto -> **Skapa användarnamn automatiskt baserat på kundens e-postadress (ibockat)** 
- WP Admin -> WooCommerce -> Inställningar -> Kundkonton -> Skapa konto -> **Skapa ett kundlösenord automatiskt (ibockat)** 
- WP Admin -> WooCommerce -> Inställningar -> Till kassan -> Kassaprocess -> **Aktivera gästköp (ej ibockat)** 

Detta resulterar i att följande påståenden är sanna:
- Alla besökare med en eller fler produkter i varukorgen kan se kassasidan, inloggad eller ej
- Alla besökare kan köpa från sajten utan att först behöva genomgå en registreringsprocess
- Återkommande kunder som sedan tidigare har ett konto kan bekvämt logga in från kassasidan utan att stoppas i ett tidigare skede (vilket kan sänka konverteringsgraden)
- Besökare som faktiskt gillar att manuellt skapa ett konto innan köp kan göra så från Mitt konto-sektionen
- Alla betalande kunder har ett kundkonto, vare sig de har registrerat ett manuellt eller fått ett automatiskt vid ett första köp
