### ISSUE TITLE
Order note not bein send to Klarna or stored in WC for KCO

### ISSUE THREAD

**Issue by slobodan** [krokedil/woocommerce-gateway-klarna#31]
### Expected behavior

Order note entered in KCO cart widget is sent to Klarna and saved in WC

### Actual behavior

Nope

**Comment by NiklasHogefjord** [comment]
@slobodan, the order note is not supposed to be sent to Klarna from what I remember. 

Tested on demo.krokedil.se/klarna and it works as expected.

**Comment by boozebrorsan** [comment]
Maybe we should close this then?
