### ISSUE TITLE
Product prices with discounts (Woocommerce & KCO) bug?

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/woocommerce-gateway-klarna#35]
Discounted price is shown at cart, but Klarna Checkout fetches the full price.
They are using regular discounts in WooCommerce. It's targeted for specific group of customers. Works for Finland but in Swe site the issue arises.

**Comment by SirRahikkala** [comment]
This can be closed now. The issue was settings misconfiguration of HTTPS/SSL.

**Comment by slobodan** [comment]
@SirRahikkala glad you solved it, thanks for letting us know.
