### ISSUE TITLE
Update arguments for the filters woocommerce_cart_item_quantity

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/woocommerce-gateway-klarna#37]
In the checkout when using KCO and Composite Products the plugin throws an warning in the cart.

Here is a suggestion from the YITH Composite Products plugin to fix this:

echo apply_filters( 'woocommerce_cart_item_quantity', $product_quantity, $cart_item_key , $cart_item );

**Comment by slobodan** [comment]
Please assign back to me after you have emailed me YITH plugin.
