### ISSUE TITLE
Ending / needed in the specified KCO checkout page url to be able to load css & js-file

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/woocommerce-gateway-klarna#41]
At https://devif.senson.no we stumbled upon a problem where the KCO css- and js-file wasn't enqueued. Everything looked ok in the settings. 

When we added an ending / to the specified KCO-page url in the settings, the checkout page worked as expected. But now an error notice in the top of the settings page is displayed saying "The specified url is not a valid WordPress url" (or similar).

**Comment by NiklasHogefjord** [comment]
How come you closed this @slobodan? Wasn't it a bug?

**Comment by slobodan** [comment]
It was :)

Fixed in develop branch
