### ISSUE TITLE
Coupons not calculating order totals correctly (in US)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#42]
### Expected behavior
Coupons (all 4 kinds: product, product %, cart, & cart %) should be handled correctly for total order_amount.  Cart discounts should also be listed as a separate order line item in the Klarna order for the US. 
-

### Actual behavior

-

### Steps to reproduce the behavior
1. add Happy Ninja t-shirt to cart: https://elkrokedilo.com/klarna-us/product/happy-ninja/
2. in cart page, add coupon 'kristi' (which provides a $2 cart discount).  order_amount should be 2130, tax 130 (for Ohio), shipping 400, discount 200, product 1800
3.  see order https://elkrokedilo.com/klarna-us/wp-admin/post.php?post=235&action=edit where order total in Woo is $21.04
4. Klarna order has order_total of 2130
see https://api-na.playground.klarna.com/ordermanagement/v1/orders/656355a9-0940-5153-a94c-31393a510e8f

{
  "order_id": "656355a9-0940-5153-a94c-31393a510e8f",
  "status": "AUTHORIZED",
  "fraud_status": "ACCEPTED",
  "order_amount": 2130,
  "original_order_amount": 2130,
  "captured_amount": 0,
  "refunded_amount": 0,
  "remaining_authorized_amount": 2130,
  "purchase_currency": "USD",
  "locale": "en-US",
  "order_lines": [
    {
      "reference": "37",
      "type": "physical",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Happy Ninja",
      "total_amount": 1600,
      "unit_price": 1800,
      "total_discount_amount": 200,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    },
    {
      "reference": "flat_rate:1",
      "type": "shipping_fee",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Flat Rate",
      "total_amount": 400,
      "unit_price": 400,
      "total_discount_amount": 0,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    },
    {
      "reference": "Sales Tax",
      "type": "sales_tax",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Sales Tax",
      "total_amount": 130,
      "unit_price": 130,
      "total_discount_amount": 0,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    }
  ],
  "merchant_reference1": "235",
  "merchant_reference2": null,
  "klarna_reference": "56L4LRCF",

-

### WordPress version
4.7.2
-

### WooCommerce version
2.6.13
-

### Klarna country
US

![woo coupon order 235](https://cloud.githubusercontent.com/assets/15654455/22694721/5320c5bc-ed16-11e6-80c0-506d104c7369.png)

-

**Comment by slobodan** [comment]
Fixed in develop branch, here's a working order

https://elkrokedilo.com/klarna-us/wp-admin/post.php?post=254&action=edit

**Comment by kristibarbosky** [comment]
on wptest store, coupon amount doubled in the iframe details, but not doubled when the order is placed with Klarna
![woo coupon order 235](https://cloud.githubusercontent.com/assets/15654455/24413875/c8617d3e-13aa-11e7-9704-1f14d3715e57.png)

**Comment by kristibarbosky** [comment]
Tested with again with master commit today with a clean demo store & clean KCO install.  Coupon was not doubled so this ticket can be closed.  

![image](https://cloud.githubusercontent.com/assets/15654455/25097778/eb148ffa-2373-11e7-9554-100feaea5c36.png)

Before closing, assigning back to @slobodan though to confirm that in the new KCO v3 plugin, US discounts will be listed as their own order line item (with a $0 amount).  Currently the cart discount was listed on the order line item (due to Woo's handling of coupons) and no separate order line item for discount:

{
  "order_id": "3a5ee642-c6bd-67ae-82eb-8b584d244d7c",
  "status": "AUTHORIZED",
  "fraud_status": "ACCEPTED",
  "order_amount": 5604,
  "original_order_amount": 5604,
  "captured_amount": 0,
  "refunded_amount": 0,
  "remaining_authorized_amount": 5604,
  "purchase_currency": "USD",
  "locale": "en-US",
  "order_lines": [
    {
      "reference": "2352555",
      "type": "physical",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Green Polka Dot T-Shirt",
      "total_amount": 2799,
      "unit_price": 2999,
      "total_discount_amount": 200,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    },
    {
      "reference": "flat_rate:1",
      "type": "shipping_fee",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Flat rate",
      "total_amount": 2500,
      "unit_price": 2500,
      "total_discount_amount": 0,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    },
    {
      "reference": "Sales Tax",
      "type": "sales_tax",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Sales Tax",
      "total_amount": 305,
      "unit_price": 305,
      "total_discount_amount": 0,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    }
  ],
  "merchant_reference1": "17",
  "merchant_reference2": null,
  "klarna_reference": "GSJ0GV4W",

**Comment by slobodan** [comment]
@kristibarbosky new plugin will mirror how it's done in KP
