### ISSUE TITLE
Wrong tax calculations on refunds in Klarna Online

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/woocommerce-gateway-klarna#47]
When doing a refund in WooCommerce the EXKL. MOMS price gets calculated the wrong way in Klarna Online.

---

**1.** The order has been activated through WooCommerce and all looks good in Klarna Online:

![skarmavbild 2017-03-08 kl 12 43 17](https://cloud.githubusercontent.com/assets/2573170/23702744/d83cf214-03fc-11e7-80a5-01f032836fd6.png)

---

**2.** When using the refund (refund is typed in at the field in the bottom in the WooCommerce order) on 1050 SEK (including tax). Now Klarna Online looks like this:

![skarmavbild 2017-03-08 kl 12 37 34](https://cloud.githubusercontent.com/assets/2573170/23702694/a37e2a70-03fc-11e7-9eba-53449df36a91.png)

The Exkl. Moms price should be 840 SEK and not 843,44 SEK.

---

**3.** All the way the actuall WooCommerce order looks fine:

![skarmavbild 2017-03-08 kl 12 48 32](https://cloud.githubusercontent.com/assets/2573170/23702915/9fbe015c-03fd-11e7-8a94-797c112741bd.png)

**Comment by slobodan** [comment]
Fixed in develop.
