### ISSUE TITLE
Adding Support for Composite Products plugin

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/woocommerce-gateway-klarna#51]
Add support for Composite Products plugin in our Klarna-plugin.

Orders from WC (when a product is Composite Product) is correct in Klarna Online but the WC order has no value and contains no order lines in the backend of WooConnerce.

**Comment by slobodan** [comment]
Not sure if this was due to an old version of Composite Products plugin, but I just tested and it looks fine.

![screen shot 2017-04-24 at 14 32 11](https://cloud.githubusercontent.com/assets/129607/25337129/d5fdccb2-28fa-11e7-96f0-9462a012baf7.png)
