### ISSUE TITLE
Coupon adding breaks the KCO page

### ISSUE THREAD

**Issue by juhosyrj** [krokedil/woocommerce-gateway-klarna#52]
Hey,

The following line (in file class-klarna-to-wc.php, line 752) breaks KCO page:
$wc_order_id = $order->get_id(); breaks the KCO page.

From debug log:
...
04-10-2017 @ 10:06:04 - 0.37132300 1491818764: Finished adding shipping to order 150...
04-10-2017 @ 10:06:04 - 0.37184700 1491818764: Adding tax rows to order 150...
04-10-2017 @ 10:06:04 - 0.37196600 1491818764: Finished adding tax rows to order 150...
04-10-2017 @ 10:06:04 - 0.37250400 1491818764: Adding coupons to order 150...

Stops there.

Changing the line to $wc_order_id = $order->id; resolves the issue.

Klarna module: 2.3.5
WC: 	2.6.14
WP: 4.7.3

**Comment by slobodan** [comment]
Thanks @juhosyrj fixing this right away
