### ISSUE TITLE
WooCommerce Gateway Klarna can't create a user account

### ISSUE THREAD

**Issue by MichaelBengtsson** [krokedil/woocommerce-gateway-klarna#53]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- User account should be made for guest customers upon fulfilling an order

### Actual behavior

- User account is not made. Klarna logs show that its due to a lack of password when creating the user

### Steps to reproduce the behavior

- Make a purchase with Klarna Checkout in a store as a guest

### Klarna plugin version

- 2.3.6

### WordPress version

- 4.7.3

### WooCommerce version

- 3.0.1

### Klarna country

- Tested on norwegian store

[klarna log excerpt.txt](https://github.com/krokedil/woocommerce-gateway-klarna/files/912369/klarna.log.excerpt.txt)

**Comment by bersens** [comment]
Hi,

Set Woocommerce settings:
- Create automatic password upon costumer creation,
