### ISSUE TITLE
Product Add-On information is unreadable in Klarna account

### ISSUE THREAD

**Issue by ValeDeOro** [krokedil/woocommerce-gateway-klarna#57]
When purchasing a product with a Product Add-On, the order information in the Klarna account is shown like this: 

![](http://cld.wthms.co/I304+)
Link to screenshot: http://cld.wthms.co/I304

Instead of "Material: Gold", it looks like gibberish to the customer. 

Within WooCommerce everything looks fine (order screen etc). 

This started happening with WooCommerce 3.0 updates. 

Ticket: 565107-zd-woothemes

### Steps to reproduce the behavior

1. Create a product with Product Add-on Options
2. Purchase product through Klarna
3. Check product information in Klarna. 

WP Version: 4.7.3
WC Database Version: 3.0.3
WooCommerce: by Automattic – 3.0.3
WooCommerce Product Add-ons: by WooCommerce – 2.8.1
WooCommerce Klarna Gateway: by WooCommerce – 2.3.6

**Comment by slobodan** [comment]
@ValeDeOro how can I create product with Product Add-on Options?

**Comment by ValeDeOro** [comment]
Oh true! You can download the plugin for this [here](http://cld.wthms.co/buUv)

This is how to set it up: https://docs.woocommerce.com/document/product-add-ons/

**Comment by ValeDeOro** [comment]
Another ticket affected: 565801-zd-woothemes

**Comment by slobodan** [comment]
Fixed for next release of our plugin, but the issue actually originates from how Add-on plugin adds data to cart items:

```$name .= ' (' . wc_price( get_product_addon_price_for_display( $addon['price'], $cart_item['data'], true ) ) . ')';```

This will automaticall add HTML tags to cart item data, since wc_price is used:

```Addon (<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#107;&#114;</span>&nbsp;4.48</span>)```

WooCommerce will then escape this code in WC_Cart class.

The fix I added passes the escaped string through html_entity_decode, then strips tags from it.

From what I see, there is no better way to do this, and this setup feels silly - adding HTML code with wc_price, escaping it, decoding it, then removing the code.

Please tell me I'm missing something and it is possible to get Add-on product title without HTML tags in it.

**Comment by ValeDeOro** [comment]
Thanks Slobodan. I will pass the information to our Product Add On devs, so they can look into it. 

Any idea when the fix will be released to the public?

**Comment by slobodan** [comment]
@ValeDeOro most likely by the end of the week, but it's available now in develop branch of this repo.

**Comment by ValeDeOro** [comment]
(just for reference reasons, ticket affected: 565107-zd-woothemes)

I have shared .develop with them :)

**Comment by ValeDeOro** [comment]
Related: 569933-zd-woothemes

After sharing .develop with them, this is the result: 

> home/hildaofs/domains/hildaofsweden.se/wp-content/plugins/woocommerce-gateway-klarna/classes/class-wc-to-klarna.php on line 610

> Warning: Invalid argument supplied for foreach() in /home/hildaofs/domains/hildaofsweden.se/wp-content/plugins/woocommerce-gateway-klarna/classes/class-wc-to-klarna.php on line 640

Can you have a look @slobodan?

**Comment by ValeDeOro** [comment]
And another one 571971-zd-woothemes

Which branch is the right one to share at this point?

**Comment by slobodan** [comment]
@ValeDeOro what's the full error from line 610?

**Comment by slobodan** [comment]
And it's still develop branch, what you have listed here is unrelated to Product add-on information

**Comment by ValeDeOro** [comment]
> what's the full error from line 610?
Asked for screenshot / error log / exact description, as this was the complete warning they sent.

**Comment by ValeDeOro** [comment]
Here you go: 

![](http://cld.wthms.co/QbsS0+)
Link to screenshot: http://cld.wthms.co/QbsS0

@slobodan
