### ISSUE TITLE
https://cdn.klarna.com/1.0/code/client/all.js?ver=1.0 should only be included if actually needed.

### ISSUE THREAD

**Issue by LarsBuur** [krokedil/woocommerce-gateway-klarna#63]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior
https://cdn.klarna.com/1.0/code/client/all.js?ver=1.0 should only be included if actually needed.
-

### Actual behavior
Google PageSpeed Insights complaints that we should Eliminate render-blocking JavaScript and CSS in above-the-fold content. 

The only script left is https://cdn.klarna.com/1.0/code/client/all.js?ver=1.0 which is included in /classes/class-klarna-payment-method-widget.php 

It seems that there once were something in place to only include it when needed - but now it included always which seems silly and odd. 
-

### Steps to reproduce the behavior
Install plugin - check html source.
-

### Klarna plugin version
2.3.6

-

### WordPress version
4.7
-

### WooCommerce version
3.0.5
-

### Klarna country
SE
-

**Comment by slobodan** [comment]
Thanks for reporting this @LarsBuur, fix will be part of next release
