### ISSUE TITLE
Addon choice do not show in order confirmation when checking out with Klarna

### ISSUE THREAD

**Issue by ValeDeOro** [krokedil/woocommerce-gateway-klarna#64]
After Klarna checkout, the order confirmation in WooCommerce as well as the order confirmation email do not state the chosen Product Add-Ons. 

### Expected behavior

After paying a product with product add-ons via Klarna, the chosen add-ons should be mentioned in the order confirmation. 

### Actual behavior

The addons work on the site and show in the cart and checkout. BUT In the woocommerce order and the order confirmation (sent by email) the addon choice is not mentioned at all. The price is correct but no information about the choice of addon.

### Steps to reproduce the behavior

Create a product with different add-on options. 
Purchase the product and pay with Klarna.
Check the confirmation email. 

You can find the debug.log here: http://cld.wthms.co/sWPsI

### Klarna plugin version

2.3.6

### WordPress version

4.7.4

### WooCommerce version

3.0.5

### Klarna country

Sweden

### Ticket

571971-zd-woothemes

**Comment by slobodan** [comment]
Fixed in previous release
