### ISSUE TITLE
Prefill KCO with customer address data if customer is logged in

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/woocommerce-gateway-klarna#67]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce the behavior

-

### Klarna plugin version

-

### WordPress version

-

### WooCommerce version

-

### Klarna country

-

**Comment by slobodan** [comment]
We do this already, only works if test mode is NOT active.
