### ISSUE TITLE
Orders empty in WC 3.0

### ISSUE THREAD

**Issue by rasmusbe** [krokedil/woocommerce-gateway-klarna#68]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- Order with address, order lines and other order data

### Actual behavior

- Empty order

### Steps to reproduce the behavior

- Install WooCommerce 3.0
- Make a purchase

### Klarna plugin version

- 2.3.6

### WordPress version

- 4.7.4

### WooCommerce version

- 3.0.6

### Klarna country

- SE

**Comment by slobodan** [comment]
@rasmusbe do you have a staging site where I could check?

**Comment by rasmusbe** [comment]
Works in 2.3.10 👍
