### ISSUE TITLE
Fatal error on thank you page

### ISSUE THREAD

**Issue by metuza** [krokedil/woocommerce-gateway-klarna#69]
I have a few plugins that add an action in the following woocommerce action, using 3 parameters:
do_action( 'woocommerce_checkout_order_processed', $order_id, $posted_data, $order );

And the problem is that Woocommerce Gateway Klarna use this action with only 1 parameter. The file is thank-you.php at line 113 - woocommerce-gateway-klarna/includes/checkout/.

And this generate a fatal error on the thank you page.

### Klarna plugin version

- Latest version 2.3.7

### WordPress version

- Latest version 4.7.4

### WooCommerce version

- Latest version 3.0.6

### Klarna country

- Norway

**Comment by slobodan** [comment]
Fixed in 2.3.8
