### ISSUE TITLE
Orders edited/completed in order editor does not update order in Klarna account

### ISSUE THREAD

**Issue by MichaelBengtsson** [krokedil/woocommerce-gateway-klarna#74]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- Order should be updated in Klarna account

### Actual behavior

- Orders edited/completed in order editor does not update order in Klarna account

### Steps to reproduce the behavior

- Edit or complete an order in the order editor. 

### Klarna plugin version

- 2.3.8

### WordPress version

- Unknown

### WooCommerce version

- 3.0.7

### Klarna country

-

**Comment by slobodan** [comment]
Waiting for more details in the original ticket
