### ISSUE TITLE
Tax not sent to Klarna for some merchants

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/woocommerce-gateway-klarna#8]
### Expected behavior

-

### Actual behavior
After v2.2 one stor have reported that tax isn't sent to Klarna for. I have access to their test environment and I can reproduce the issue. The tax disappear in the step after the email address and postal number is entered in the KCO iframe, e.g. when your address and the available payment options are displayed.

**Comment by slobodan** [comment]
Seems to happen when "Round tax at subtotal level, instead of rounding per line" is checked in Tax settings.
