### ISSUE TITLE
Orders via Klarna Checkout receive an order total of 0 kr

### ISSUE THREAD

**Issue by richardsweeney** [krokedil/woocommerce-gateway-klarna#82]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

After an order has been submitted upon returning to the thank you page all call to `$order->get_total();` returns a value of 0.

### Actual behavior

The order total should be the correct value :)

The order total is correct when the status of the order is updated.

### Steps to reproduce the behavior

Place an order, go to the thank you page. Dump the value of `$order->get_total();`.

### Klarna plugin version

2.3.10

### WordPress version

4.7.5

### WooCommerce version

3.0.7

### Klarna country

Sweden

**Comment by slobodan** [comment]
@richardsweeney does this only happen when you manually try to dump the value of ```$order->get_total()``` or does the issue also exist when viewing an order in backend?

**Comment by richardsweeney** [comment]
Sorry I never got back to you about this. It seems to be solved as of the latest release.
