### ISSUE TITLE
Fees added via WC_Cart::add_fee() generate fatal error in WC_Gateway_Klarna_Order::process_fees()

### ISSUE THREAD

**Issue by jamesinglis** [krokedil/woocommerce-gateway-klarna#84]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

- When running WC_Gateway_Klarna_Order->process_fees(), a manually added fee should be processed as normal in WC_Gateway_Klarna_Order::process_fees() when you try to complete the checkout.

### Actual behavior

- When running WC_Gateway_Klarna_Order::process_fees(),a manually added fee throws a fatal error in WC_Gateway_Klarna_Order::process_fees() when you try to complete the checkout.

PHP Fatal error:  Uncaught Error: Call to a member function get_sku() on boolean in /nas/content/live/example/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-order.php:225

Stack trace:
#0 /nas/content/live/example/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-order.php(55): WC_Gateway_Klarna_Order->process_fees()
#1 /nas/content/live/example/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-invoice.php(655): WC_Gateway_Klarna_Order->prepare_order(Array, Array, 'no')
#2 /nas/content/live/example/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(785): WC_Gateway_Klarna_Invoice->process_payment(17679)
#3 /nas/content/live/example/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(962): WC_Checkout->process_order_payment(17679, 'klarna_invoice')
#4 /nas/content/live/example/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(390): WC_Checkout->process_checkout()
#5 [internal function]: WC_AJAX::checkout('')
#6 /nas/content/live/bassen in /nas/content/live/example/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-order.php on line 225, referer: https://www.example.no/checkout

The problem is from line 220 to line 226 of classes/class-klarna-order.php - a boolean check is made on line 220 to see if $invoice_fee_product exists/is a product object, or is false. After this conditional check, a new conditional check is made which makes the assumption that $invoice_fee_product is not false, and generates the fatal error if it is. If this second conditional is moved to inside the "true" condition of the first, the logic works correctly and everything works.

### Steps to reproduce the behavior

- Add the following hook:

function woocommerce_checkout_add_handling_fee(WC_Cart $cart)
{
    if (is_admin() && !defined('DOING_AJAX'))
        return;

    $fee = 76.00;
        $cart->add_fee('Processing Fee', $fee, true);
    }
}

add_action('woocommerce_cart_calculate_fees', 'woocommerce_checkout_add_handling_fee', 10, 1);

Go to checkout and select pay by Faktura, complete the fields (even with a dummy personal number) and click "Place Order".

### Klarna plugin version

- 2.3.11

### WordPress version

- 4.8

### WooCommerce version

- 3.0.9 and 3.1

### Klarna country

- Norway

**Comment by jamesinglis** [comment]
The following patch resolves the issue for me in production:
```
diff --git a/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-order.php b/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-order.php
index 401ca0f..f5af659 100644
--- a/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-order.php
+++ b/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-order.php
@@ -222,7 +222,7 @@ class WC_Gateway_Klarna_Order {
 				} else {
 					$invoice_fee_name = '';
 				}
-				if ( $invoice_fee_product->get_sku() ) {
+				if ( $invoice_fee_product !== false && $invoice_fee_product->get_sku() ) {
 					$artNo = $invoice_fee_product->get_sku();
 				}
 				else {
```

**Comment by slobodan** [comment]
Thanks for reporting this. Cleaned up this entire function a bit, and the fix is in our develop branch. Will be part of next version.
