### ISSUE TITLE
Invoice payment not working/no redirect after placing order

### ISSUE THREAD

**Issue by codeRyder** [krokedil/woocommerce-gateway-klarna#86]
### Expected behavior

Invoice payment:
After clicking the buy now/place order button, user should be redirected to order-success page and order is commited/appears in backend.

### Actual behavior

Invoice payment:
After clicking the buy now/place order button, the spinner appears, disables the button ("while processing/spinning") and disappears finally without any redirect or order commited. After that the button is active again and can be clicked once again with no success.

### Steps to reproduce the behavior

Just try to check out. We are experiencing that in some cases the checkout seems to work, because orders are commited. We tried to figure out in which case it does, but no success till now. Used Safari 10.1.1  and Firefox 54.0.1 on Mac OS Sierra

### Klarna plugin version

Version 2.3.11

### WordPress version

Version 4.8

### WooCommerce version

Version 3.0.8

### Klarna country

Germany

### Screenshots

![bildschirmfoto 2017-07-05 um 10 39 51](https://user-images.githubusercontent.com/26710874/27856420-6093d348-616e-11e7-814c-732c01abc5b2.png)

![bildschirmfoto 2017-07-05 um 10 40 13](https://user-images.githubusercontent.com/26710874/27856419-608ed2da-616e-11e7-9040-29ff781a5a26.png)

**Comment by NiklasHogefjord** [comment]
This looks like a temporary issue with Klarnas system. I'm closing this ticket.
