### ISSUE TITLE
Check compatibility with Flatsome 3.0

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/woocommerce-gateway-klarna#9]
### Expected behavior

Being able to change the quantity of each order line in the Klarna cart widget.
## 
### Actual behavior

With Flatsome the quantity can only be changed one time, after that it's disabled. I need to check why this happens so that we can send a ticket to Flatsome.

**Comment by slobodan** [comment]
We sent a support ticket to Flatsome authors, as well as the fix, since this is a bug in their theme, they were not interested. Closing the issue.
