### ISSUE TITLE
!!! Security vulnerability !!! 

### ISSUE THREAD

**Issue by grosssmutttr** [krokedil/woocommerce-gateway-klarna#92]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Steps to reproduce the behavior
1. Activate "Automatically create an account for new customers."
2. Make a guest order with an email address that already exists
3. See that you are logged in the account of that user!!!!
4. Perhaps these are the lines causing that problem /includes/checkout/thank-you.php
if ( ! is_user_logged_in() && $order->get_user_id() > 0 ) {
	wp_set_current_user( $order->get_user_id() );
	wc_set_customer_auth_cookie( $order->get_user_id() );
}
-

### Klarna plugin version
Version 2.3.5
-

### WordPress version
Version 4.8
-

### WooCommerce version
WooCommerce 3.0
-

### Klarna country
DE
-

**Comment by slobodan** [comment]
Please update Klarna plugin.

**Comment by grosssmutttr** [comment]
I don't think this is solved in the new version:
```
// Add user ID, in case listener did not do it already.
if ( $order->get_user_id() === 0 ) {
	if ( email_exists( $klarna_order['billing_address']['email'] ) ) {
		$user        = get_user_by( 'email', $klarna_order['billing_address']['email'] );
		$customer_id = $user->ID;
		update_post_meta( $order_id, '_customer_user', $customer_id );
	} else {
		// Create new user.
		$checkout_settings = get_option( 'woocommerce_klarna_checkout_settings' );
		if ( 'yes' === $checkout_settings['create_customer_account'] ) {
			$customer_id = wc_create_new_customer( $klarna_order['billing_address']['email'] );
			if ( is_int( $customer_id ) ) {
				update_post_meta( $order_id, '_customer_user', $customer_id );
			}
		}
	}
}
```
If I interprate this code correctly (/includes/checkout/thank-you.php) you simply assign the email to the user but you are not sure that the user who purchased something is the user who created this account before.

For better understanding:
1. A user called Hans creates an account with "hans@email.com" and purchases items
2. A different user makes a guest purchase with "hans@email.com" and is logged in to the account of the other person!

-> You can't simply assign a user to an account via email if you are not sure this is the user (WITHOUT PASSWORD)

**Comment by slobodan** [comment]
Fixed by restricting user login to newly created accounts only. Submitting the updated version to Klarna now. Thank you for reporting this.
