### ISSUE TITLE
Coupon usage limitation per user 

### ISSUE THREAD

**Issue by jgangso** [krokedil/woocommerce-gateway-klarna#93]
Expected behavior

Coupon which is limited to 1 time per user should not be possible to use multiple times by the same user (or billing email address if user is unregistered)

Actual behavior

One can order multiple times with same coupon and same billing email address.

Steps to reproduce the behavior

Create coupon and set limit to 1 time per user
Open inPrivate browsing and go to webshop and make a order using that coupon
Repeat step 2 using same coupon and entering same billing email address
Both times the coupon is accepted.

Klarna plugin version

2.3.11

WordPress version

4.8

WooCommerce version

3.0.8

Klarna country

NO

**Comment by jgangso** [comment]
Just noting a few observations:

Seems like WC_Cart::check_customer_coupons is never called for KCO orders. It is supposed to be called via hook woocommerce_after_checkout_validation which gets never triggered on KCO flow.

KCO seems to have own validation class WC_Gateway_Klarna_Order_Validate, where method validate_checkout_listener should perhaps also call the check_customer_coupons method to ensure coupon haven't been already been used by user in question.

However, it seems like the entire method WC_Gateway_Klarna_Order_Validate::validate_checkout_listener is never been called either. It's been mentioned on WC_Gateway_Klarna_Checkout::__construct, binding it to action woocommerce_api_wc_gateway_klarna_order_validate, but such action is never fired anywhere, thus seems like the intentioned validation is never actually done.

Does this seem like correct? Could someone from the plugin team have a look at it? @slobodan @Victor-Krokedil @NiklasHogefjord

**Comment by richardsweeney** [comment]
We have the same problem!

**Comment by slobodan** [comment]
@jgangso @richardsweeney thanks for reporting this.

I'll investigate the coupon issue and work on a fix next week.

As far as `WC_Gateway_Klarna_Order_Validate::validate_checkout_listener` is concerned, Klarna will ping registered validate URL, but ONLY if website URL is https and validate stock option is checked in Klarna Checkout settings. You can see the if statement here: 

https://github.com/krokedil/woocommerce-gateway-klarna/blob/master/includes/checkout/create.php#L135

I agree with you on `WC_Gateway_Klarna_Order_Validate::validate_checkout_listener` being the right place to check for coupons.

**Comment by slobodan** [comment]
The fix for this is in develop branch at the moment (commit: https://github.com/krokedil/woocommerce-gateway-klarna/commit/43f547cb6eb9f5cf1d1c8084ad4274f69166d7ef), submitting new release to Woo tomorrow.

**Comment by richardsweeney** [comment]
Awesome @slobodan ! Many thanks for this :)

**Comment by richardsweeney** [comment]
I've downloaded `2.4.0` but I'm still able to apply a single use coupon multiple times with Klarna Checkout. I am using it in test mode.

WP 4.8.1
WC 3.1.1

**Comment by NiklasHogefjord** [comment]
@richardsweeney Have you enabled/checked the **"Check items stock and valid shipping method during checkout"** setting? It's poorly described from our side but this setting must be activated to enable the validation feature. Previous this was a stock level and valid shipping option check, but now the coupon check is included in this as well. I will update the docs.

**Comment by richardsweeney** [comment]
@NiklasHogefjord thanks, I _just_ read that :)

Seems to be working now!

**Comment by NiklasHogefjord** [comment]
Great @richardsweeney! :)
