### ISSUE TITLE
VAT is not applied correctly on coupon codes

### ISSUE THREAD

**Issue by jelgblad** [krokedil/woocommerce-gateway-klarna#94]
### Expected behavior

Calculated VAT on coupon codes should be transferred to Klarna.

If 100 SEK coupon code is applied with 25% VAT the coupon should subtract 80 SEK from total price and 20 SEK from total VAT.

### Actual behavior

Coupon subtracts full amount from price and subtracts nothing from VAT.
VAT is calculated correctly in WooCommerce but not in Klarna Online.

_**WooCommerce:**_
![image](https://user-images.githubusercontent.com/971469/29019945-9e662db8-7b60-11e7-8b61-78f17b70a72d.png)

_**Klarna Online:**_
![image](https://user-images.githubusercontent.com/971469/29019804-174692b4-7b60-11e7-9132-310591ff427d.png)

### Steps to reproduce the behavior

1. Set product prices with VAT.
2. Activate setting "Send discounts as separate items".
3. Create coupon code with fixed amount.
4. Apply coupon code at checkout.

### Klarna plugin version

2.3.14

### WordPress version

4.8.1

### WooCommerce version

3.1.1

### Klarna country

Sweden

**Comment by slobodan** [comment]
Working on a fix, thanks for reporting @jelgblad

**Comment by slobodan** [comment]
Fixed and will be part of next version
