### ISSUE TITLE
WP_Error sent to Klarna_Checkout_BasicConnector::handleResponse() causes Fatal Error

### ISSUE THREAD

**Issue by richardsweeney** [krokedil/woocommerce-gateway-klarna#99]
I'm not sure how much you guys can affect this, but we're getting a few fatal errors a day on https://idealofsweden.com via Klarna.

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Klarna_Checkout_BasicConnector::handleResponse() must be an instance of Klarna_Checkout_HTTP_Response, instance of WP_Error given, called in /www/idealofsweden.com/releases/20170823084226/site/public/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/BasicConnector.php on line 345 and defined in /www/idealofsweden.com/releases/20170823084226/site/public/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/BasicConnector.php:253#012`

`Stack trace:#012#0 /www/idealofsweden.com/releases/20170823084226/site/public/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/BasicConnector.php(345): Klarna_Checkout_BasicConnector->handleResponse(Object(WP_Error), Object(Klarna_Checkout_Order), Array)#012#1 /www/idealofsweden.com/releases/20170823084226/site/public/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/BasicConnector.php(119): Klarna_Ch in /www/idealofsweden.com/releases/20170823084226/site/public/wp-content/plugins/woocommerce-gateway-klarna/vendor/klarna/checkout/src/Klarna/Checkout/BasicConnector.php on line 253`

The issue does seems to occur only occasionally - iDeal has around 1000 sales per day, and we get 2-4 of these daily.

### Klarna plugin version

2.4.0

### WordPress version

4.8.1

### WooCommerce version

3.1.2

### Klarna country

Sweden

**Comment by richardsweeney** [comment]
I'm guessing you might want to just check the response before returning it to the handler, if that's even something you can affect in the plugin, or is that all done via the Klarna API?

**Comment by slobodan** [comment]
@richardsweeney thanks for reporting this. I'll work on this early next week, but your suggestion to make sure the response is as expected makes sense. 

I've seen this error in the past, but it's been a very long time since it happened. Will keep you posted here.

**Comment by richardsweeney** [comment]
@slobodan looking back at logs from the summer it's a pretty regular occurrance for us. Thanks!

**Comment by slobodan** [comment]
@richardsweeney I was wrong, sorry, haven't seen this one, it was another error I meant. 

I made a change in [feature/connector-error](https://github.com/krokedil/woocommerce-gateway-klarna/tree/feature/connector-error) branch, would you mind testing to see if this solves the issue?

It throws an exception in case wp_remote_requests results in a WP_Error in WPTransport.php (which we added to the library), the same way CURLTransport.php (which is part of Klarna provided library originally) file does.

https://github.com/krokedil/woocommerce-gateway-klarna/blob/feature/connector-error/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/WPTransport.php#L107-L116

If you do test, please let me know if this works, so I can merge this for next release. The entire change is inside a is_wp_error if statement, so there should be no changes unless there's an error.

The problem would happen when plugin can't retrieve a Klarna order, for whatever reason. The reason should be logged into error log already btw. but I added a bit more to it, so it's easier to find, check L108-L109 in my last link.

**Comment by richardsweeney** [comment]
@slobodan as far as I can see this works, but the error is not easy to reproduce locally :( 

The code looks good. If you're up for it, I'd suggest you merge this in for the next release. I can keep an eye on our logs and let you know if the problem disappears.

**Comment by richardsweeney** [comment]
@slobodan as far as I can see this works, but the error is not easy to reproduce locally :( 

The code looks good. If you're up for it, I'd suggest you merge this in for the next release. I can keep an eye on our logs and let you know if the problem disappears.

**Comment by slobodan** [comment]
Thanks @richardsweeney that's great to hear. Yes, the idea is to definitely merge this change for next release. Please let me know if you notice anything unusual in meantime.

**Comment by richardsweeney** [comment]
Awesome @slobodan thanks again!
